# Generated by Django 4.2.30 on 2026-06-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת')),
                ('content', models.TextField(verbose_name='תוכן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון אחרון')),
                ('is_published', models.BooleanField(default=False, verbose_name='מפורסם')),
            ],
            options={
                'verbose_name': 'מאמר',
                'verbose_name_plural': 'מאמרים',
                'ordering': ['-created_at'],
            },
        ),
    ]
