# Generated by Django 4.2.30 on 2026-07-18 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_book_chapter_article_hebrew_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='מזהה סשן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='משתמש (אם מחובר)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=50, verbose_name='שם משפחה')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('address', models.CharField(max_length=250, verbose_name='כתובת למשלוח')),
                ('city', models.CharField(max_length=100, verbose_name='עיר')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='מיקוד (אופציונלי)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הזמנה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן לאחרונה')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='סך הכל לתשלום')),
                ('status', models.CharField(choices=[('pending', 'ממתין לתשלום (ביט/העברה בנקאית)'), ('paid', 'שולם - ממתין למשלוח'), ('shipped', 'נשלח ללקוח'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס הזמנה')),
                ('notes', models.TextField(blank=True, verbose_name='הערות להזמנה')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='hebrew_date',
        ),
        migrations.AddField(
            model_name='book',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='זמין לרכישה'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='מחיר הספר'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='מלאי זמין'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='מחיר בעת הרכישה')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.book', verbose_name='ספר')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='articles.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.book', verbose_name='ספר')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='articles.cart')),
            ],
        ),
    ]
