# Generated by Django 4.2.30 on 2026-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_parasha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parasha',
            field=models.CharField(blank=True, default=',general,', max_length=500, verbose_name='שיוך לפרשות שבוע'),
        ),
    ]
