# Generated by Django 4.2.30 on 2026-07-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_parasha'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה (1 יופיע ראשון)'),
        ),
    ]
