# Generated by Django 4.2.30 on 2026-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_book_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='שאלה')),
                ('answer', models.TextField(verbose_name='תשובה')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='קטגוריה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
            ],
            options={
                'verbose_name': 'שאלה ותשובה',
                'verbose_name_plural': 'שאלות ותשובות',
            },
        ),
    ]
