# Generated by Django 4.2.30 on 2026-07-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_qa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order', 'title']},
        ),
    ]
